---
steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        # Get version from git tag
        if [ -n "${TAG_NAME}" ]; then
          # If triggered by a tag, use tag name (remove 'v' prefix if present)
          VERSION_FROM_TAG=$(echo "${TAG_NAME}" | sed 's/^v//')
        else
          # If not triggered by tag, use git describe
          git fetch --unshallow --tags || git fetch --tags
          VERSION_FROM_TAG=$(git describe --tags --dirty --always)
        fi

        echo "Using version: $$VERSION_FROM_TAG"
        echo $$VERSION_FROM_TAG > /workspace/version.txt
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        VERSION_FROM_TAG=$(cat /workspace/version.txt)

        # Install dependencies for file manipulation
        apt-get update && apt-get install -y sed

        # Update pyproject.toml with the version
        if grep -q 'dynamic = \["version"\]' pyproject.toml; then
          # If using dynamic versioning, create a simple version file
          mkdir -p src/your_package
          echo "__version__ = '$$VERSION_FROM_TAG'" > src/your_package/_version.py
        else
          # Update static version in pyproject.toml
          sed -i "s/version = .*/version = \"$$VERSION_FROM_TAG\"/" pyproject.toml
        fi

        echo "Updated version to: $$VERSION_FROM_TAG"
        grep -A5 -B5 "version" pyproject.toml || echo "Version file created"
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "=== Installing system dependencies ==="
        apt-get update && apt-get install -y curl

        echo "=== Installing UV ==="
        curl -LsSf https://astral.sh/uv/install.sh | sh

        echo "=== Setting up UV path ==="
        # Add UV to PATH (works regardless of where it installs)
        export PATH="$$HOME/.local/bin:/root/.cargo/bin:$$PATH"

        echo "=== Verifying UV installation ==="
        which uv
        uv --version

        echo "=== Building package ==="
        uv sync --frozen --python $(which python3.11)
        uv build --python $(which python3.11)

        echo "=== Build results ==="
        ls -la dist/
        echo "Built package with version: $(cat /workspace/version.txt)"

  - name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "=== Installing system dependencies ==="
        apt-get update && apt-get install -y --no-install-recommends \
            curl ca-certificates gnupg unzip

        echo "=== Installing Google Cloud SDK ==="
        curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz -o gcloud.tar.gz
        tar -xf gcloud.tar.gz
        ./google-cloud-sdk/install.sh --quiet --path-update=false

        echo "=== Installing uv (Python package manager) ==="
        curl -LsSf https://astral.sh/uv/install.sh | sh

        export PATH="$$PWD/google-cloud-sdk/bin:$$HOME/.local/bin:/root/.cargo/bin:$$PATH"

        echo "=== Verifying installations ==="
        gcloud version
        uv --version

        # Install twine

        uv tool install twine

        # Configure twine for GCP Artifact Registry

        export TWINE_USERNAME=oauth2accesstoken

        export TWINE_PASSWORD=$(gcloud auth print-access-token)

        export TWINE_REPOSITORY_URL=https://${_REGION}-python.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/

        # Upload the built package

        ~/.local/bin/twine upload dist/*

substitutions:
  _REGION: us-central1
  _REPO_NAME: Packages for tableau-to-looker-parser
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE  # 🔧 ADDITIONAL FIX: Allow loose substitutions
