---
steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        # Get version from git tag
        if [ -n "${TAG_NAME}" ]; then
          # If triggered by a tag, use tag name (remove 'v' prefix if present)
          VERSION_FROM_TAG=$(echo "${TAG_NAME}" | sed 's/^v//')
        else
          # If not triggered by tag, use git describe
          git fetch --unshallow --tags || git fetch --tags
          VERSION_FROM_TAG=$(git describe --tags --dirty --always)
        fi

        echo "Using version: $$VERSION_FROM_TAG"
        echo $$VERSION_FROM_TAG > /workspace/version.txt
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        VERSION_FROM_TAG=$(cat /workspace/version.txt)

        # Install dependencies for file manipulation
        apt-get update && apt-get install -y sed

        # Update pyproject.toml with the version
        if grep -q 'dynamic = \["version"\]' pyproject.toml; then
          # If using dynamic versioning, create a simple version file
          mkdir -p src/your_package
          echo "__version__ = '$$VERSION_FROM_TAG'" > src/your_package/_version.py
        else
          # Update static version in pyproject.toml
          sed -i "s/version = .*/version = \"$$VERSION_FROM_TAG\"/" pyproject.toml
        fi

        echo "Updated version to: $$VERSION_FROM_TAG"
        grep -A5 -B5 "version" pyproject.toml || echo "Version file created"
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "=== Installing system dependencies ==="
        apt-get update && apt-get install -y curl

        echo "=== Installing UV ==="
        curl -LsSf https://astral.sh/uv/install.sh | sh

        echo "=== Setting up UV path ==="
        # Add UV to PATH (works regardless of where it installs)
        export PATH="$$HOME/.local/bin:/root/.cargo/bin:$$PATH"

        echo "=== Verifying UV installation ==="
        which uv
        uv --version

        echo "=== Building package ==="
        uv sync --frozen --python $(which python3.11)
        uv build --python $(which python3.11)

        echo "=== Build results ==="
        ls -la dist/
        echo "Built package with version: $(cat /workspace/version.txt)"

substitutions:
  _REGION: us-central1
  _REPO_NAME: Packages for tableau-to-looker-parser
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE  # 🔧 ADDITIONAL FIX: Allow loose substitutions
