#!/usr/bin/env python3
"""
Test script to compare original view generator vs sqlparse view generator.
"""

import sys
import tempfile
import shutil
from pathlib import Path

sys.path.insert(0, "src")

from tableau_to_looker_parser.generators.lookml_generator import LookMLGenerator
from tableau_to_looker_parser.generators.view_generator_sqlparse import (
    ViewGeneratorSQLParse,
)
from tableau_to_looker_parser.generators.template_engine import TemplateEngine
from tableau_to_looker_parser.core.migration_engine import MigrationEngine


def test_both_generators():
    """Test both generators and compare outputs."""

    print("Comparing Original vs SQLParse View Generators")
    print("=" * 60)

    # Generate JSON from book7_calc.twb
    book_name = "book7_calc.twb"
    twb_file = Path(f"sample_twb_files/{book_name}")

    if not twb_file.exists():
        print(f"❌ Test file not found: {twb_file}")
        return

    print(f"📁 Processing: {twb_file}")

    # Get migration data
    engine = MigrationEngine()
    data = engine.migrate_file(str(twb_file), str(twb_file.parent))

    print("📊 Migration data loaded:")
    print(f"   - Tables: {len(data.get('tables', []))}")
    print(f"   - Dimensions: {len(data.get('dimensions', []))}")
    print(f"   - Measures: {len(data.get('measures', []))}")
    print(f"   - Calculated Fields: {len(data.get('calculated_fields', []))}")

    # Test 1: Original Generator
    print("\n🔄 Testing Original Generator...")
    try:
        original_generator = LookMLGenerator()

        with tempfile.TemporaryDirectory() as temp_dir:
            original_files = original_generator.generate_project_files(data, temp_dir)

            # Copy original files
            original_output_dir = Path("sample_twb_files/comparison_original")
            original_output_dir.mkdir(exist_ok=True)

            shutil.copy2(original_files["model"], original_output_dir / "model.lkml")
            for view_file in original_files["views"]:
                view_name = Path(view_file).stem
                shutil.copy2(view_file, original_output_dir / f"{view_name}.lkml")

            print("✅ Original generator completed")
            print(f"   📂 Output saved to: {original_output_dir}")

    except Exception as e:
        print(f"❌ Original generator failed: {e}")
        return

    # Test 2: SQLParse Generator
    print("\n🔄 Testing SQLParse Generator...")
    try:
        template_engine = TemplateEngine()
        sqlparse_view_gen = ViewGeneratorSQLParse(template_engine)

        with tempfile.TemporaryDirectory() as temp_dir:
            # Generate only views (not full project)
            sqlparse_views = sqlparse_view_gen.generate_views(data, temp_dir)

            # Copy sqlparse files
            sqlparse_output_dir = Path("sample_twb_files/comparison_sqlparse")
            sqlparse_output_dir.mkdir(exist_ok=True)

            for view_file in sqlparse_views:
                view_name = Path(view_file).stem
                shutil.copy2(view_file, sqlparse_output_dir / f"{view_name}.lkml")

            print("✅ SQLParse generator completed")
            print(f"   📂 Output saved to: {sqlparse_output_dir}")

    except Exception as e:
        print(f"❌ SQLParse generator failed: {e}")
        import traceback

        traceback.print_exc()
        return

    # Compare outputs
    print("\n🔍 Comparing Outputs...")
    compare_generated_files(original_output_dir, sqlparse_output_dir)


def compare_generated_files(original_dir: Path, sqlparse_dir: Path):
    """Compare the generated files from both approaches."""

    print("\n📋 File Comparison:")
    print(f"   Original: {original_dir}")
    print(f"   SQLParse: {sqlparse_dir}")

    # Get list of files from both directories
    original_files = set(f.name for f in original_dir.glob("*.lkml"))
    sqlparse_files = set(f.name for f in sqlparse_dir.glob("*.lkml"))

    print("\n📁 Files Generated:")
    print(f"   Original: {len(original_files)} files - {sorted(original_files)}")
    print(f"   SQLParse: {len(sqlparse_files)} files - {sorted(sqlparse_files)}")

    # Compare common files
    common_files = original_files & sqlparse_files
    print(f"\n🔄 Comparing {len(common_files)} common files...")

    for filename in sorted(common_files):
        if filename == "model.lkml":
            continue  # Skip model file (only generated by original)

        print(f"\n--- Comparing {filename} ---")
        compare_single_file(original_dir / filename, sqlparse_dir / filename)


def compare_single_file(original_file: Path, sqlparse_file: Path):
    """Compare two LookML files and highlight differences."""

    try:
        with open(original_file, "r") as f:
            original_content = f.read()

        with open(sqlparse_file, "r") as f:
            sqlparse_content = f.read()

        # Count calculated fields
        original_calc_fields = original_content.count("# Original Tableau formula:")
        sqlparse_calc_fields = sqlparse_content.count("# Original Tableau formula:")

        # Count migration errors
        original_errors = original_content.count("MIGRATION ERROR")
        sqlparse_errors = sqlparse_content.count("MIGRATION ERROR")

        # Count successful conversions (fields with proper SQL)
        original_success = original_content.count("${TABLE}.")
        sqlparse_success = sqlparse_content.count("${TABLE}.")

        print("   📊 Statistics:")
        print(
            f"      Calculated Fields - Original: {original_calc_fields}, SQLParse: {sqlparse_calc_fields}"
        )
        print(
            f"      Migration Errors  - Original: {original_errors}, SQLParse: {sqlparse_errors}"
        )
        print(
            f"      Successful Conv   - Original: {original_success}, SQLParse: {sqlparse_success}"
        )

        # Show first few lines of each for quick comparison
        original_lines = original_content.split("\n")[:10]
        sqlparse_lines = sqlparse_content.split("\n")[:10]

        print("   📄 First 10 lines comparison:")
        print(
            f"      Original preview: {original_lines[0] if original_lines else 'Empty'}"
        )
        print(
            f"      SQLParse preview: {sqlparse_lines[0] if sqlparse_lines else 'Empty'}"
        )

        # Quick diff check
        if original_content.strip() == sqlparse_content.strip():
            print("   ✅ Files are identical!")
        else:
            print("   ⚠️  Files differ")

            # Show a sample difference (first calculated field)
            show_sample_difference(original_content, sqlparse_content)

    except Exception as e:
        print(f"   ❌ Error comparing files: {e}")


def show_sample_difference(original_content: str, sqlparse_content: str):
    """Show a sample of the differences between files."""

    # Find first calculated field in each
    original_lines = original_content.split("\n")
    sqlparse_lines = sqlparse_content.split("\n")

    # Look for first measure or dimension with sql
    original_sample = None
    sqlparse_sample = None

    for i, line in enumerate(original_lines):
        if "measure:" in line or "dimension:" in line:
            # Get next 5 lines
            original_sample = "\n".join(original_lines[i : i + 6])
            break

    for i, line in enumerate(sqlparse_lines):
        if "measure:" in line or "dimension:" in line:
            # Get next 5 lines
            sqlparse_sample = "\n".join(sqlparse_lines[i : i + 6])
            break

    if original_sample and sqlparse_sample:
        print("\n   📝 Sample Difference:")
        print("      Original:")
        for line in original_sample.split("\n"):
            print(f"        {line}")
        print("      SQLParse:")
        for line in sqlparse_sample.split("\n"):
            print(f"        {line}")


if __name__ == "__main__":
    test_both_generators()

    print("\n" + "=" * 60)
    print("🎯 COMPARISON COMPLETE")
    print("=" * 60)
    print("Check the generated files in:")
    print("  📂 sample_twb_files/comparison_original/")
    print("  📂 sample_twb_files/comparison_sqlparse/")
    print("\nLook for differences in:")
    print("  ✅ Number of successfully converted fields")
    print("  ❌ Number of migration errors")
    print("  🔧 Quality of generated SQL")
